### ISSUE TITLE
Sites metadata aren't completely rendered

### ISSUE THREAD

**Issue by sultanpeyek** [The-Great-Ape/unlimitedgrapes.com#1]
Hello Greetings @tommaay 
Great job on the website it's so dope man (unfortunately since it's built on Webflow then I can't contribute any 😆).

I'd like to inform some area to improve so the website can go more lit.
We need to polish the site metada to pass the [Facebook Share Debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.unlimitedgrapes.com%2F) and [Twitter Card Validator](https://cards-dev.twitter.com/validator).

If we managed to pass that validator, our sites could be shared beautifully across any channel.

Here's the example of the codes that I'm not sure where to add in Webflow (this was my [unmerged PR](https://github.com/grapemaster/unlimitedgrapes.com/pull/2) from the old website, you can modify it 😃) 

```
    <title>The Great Ape grape solana hackathon $grape token</title>
    <link rel="canonical" href="https://unlimitedgrapes.com/" />
    <meta name="description" content="Community token for the Solana Blockchain" />
    <meta property="og:url" content="https://unlimitedgrapes.com/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="The Great Ape grape solana hackathon $grape token" />
    <meta property="og:description" content="Community token for the Solana Blockchain" />
    <meta property="og:image" itemprop="image" content="https://unlimitedgrapes.com/assets/img/og-image.png" />
    <meta property="og:image:secure_url" content="https://unlimitedgrapes.com/assets/img/og-image.png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@solanagrape" />
    <meta name="twitter:creator" content="@solanagrape" />
    <meta name="twitter:url" content="https://unlimitedgrapes.com/" />
    <meta name="twitter:title" content="The Great Ape grape solana hackathon $grape token" />
    <meta name="twitter:description" content="Community token for the Solana Blockchain" />
    <meta name="twitter:image" content="https://unlimitedgrapes.com/assets/img/og-image.png" />
```

cc: @Lefti-t 🙇

**Comment by tommaay** [comment]
Hey @sultanpeyek thanks for your suggestion! For the title and meta tags all you have to do is add them inside of <head> right?

**Comment by sultanpeyek** [comment]
Yes @tommaay I think Webflow has that capabilities (to add the Title and Meta Description), but I'm not sure where to add the og and twitter card tags using Webflow.

**Comment by tommaay** [comment]
@sultanpeyek Do you want me to add what you had for the previous site or will the meta tags be different for the new site?

**Comment by sultanpeyek** [comment]
Hello zup bro @tommaay, sorry I didn't enable notification on my github email 😓 
No bro, I just gave you the example, you can modify the value that suit the current site 👍
